### ISSUE TITLE
CMake not falling back to default language

### ISSUE THREAD

**Issue by tony** [IonicaBizau/github-colors#26]
Apparently CMake may not have a default color on file.

This is on my site with github-colors at 2.2.16

I've narrowed it down, with PHP, CMake, and "fakeLang", with ``handleOthers`` set to ``true``:

```javascript
        console.log(
          colors.get('PHP', true).color,
          colors.get('CMake', true).color,
          colors.get('fakeLanguage', true).color,
        );
```

Output:  ``#4F5D95 undefined #ccc``

**Comment by tony** [comment]
To clarify, ``CMake`` is a language covered by GH

<img width="1201" alt="screen shot 2018-02-16 at 11 49 01 am" src="https://user-images.githubusercontent.com/26336/36321857-e6af129a-1310-11e8-96d9-51753f7f738c.png">

**Comment by IonicaBizau** [comment]
Good point! 

It seems like `cmake` doesn't have a `color` field: https://github.com/IonicaBizau/github-colors/blob/669946eea3d2817691ce48622c1838f8adec4c21/dist/24-12-2017/colors.json#L654-L667

**Comment by IonicaBizau** [comment]
Opened https://github.com/github/linguist/issues/4041
